---

- apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    filename: sublime-text
    state: present

- apt: 
    name: sublime-text
    state: latest
